/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pseudoınverse;

/**
 *
 * @author aarslan
 */
public class MatrisOlustur extends javax.swing.JFrame {
    int m;
    int n;
    double matrix[][];
    /**
     * Creates new form MatrisOlustur
     */
    public MatrisOlustur(int m,int n) {
        this.m = m;
        this.n = n;
        this.matrix = new double[5][5];
        initComponents();
        jTextField26.setEditable(false);
        matrisolusturma();
}
    public MatrisOlustur(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("İşleme Başla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MATRİS OLUŞTUR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField21, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                            .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                            .addComponent(jTextField23, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField16)
                    .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void matrisolusturma(){
       if(this.m < 5){
           jTextField21.setVisible(false);
           jTextField22.setVisible(false);
           jTextField23.setVisible(false);
           jTextField24.setVisible(false);
           jTextField25.setVisible(false);
       }
       if(this.m < 4) {
           jTextField16.setVisible(false);
           jTextField17.setVisible(false);
           jTextField18.setVisible(false);
           jTextField19.setVisible(false);
           jTextField20.setVisible(false);
       }
       if(this.m < 3 ) {
           jTextField11.setVisible(false);
           jTextField12.setVisible(false);
           jTextField13.setVisible(false);
           jTextField14.setVisible(false);
           jTextField15.setVisible(false);
       }
       if(this.m < 2 ){
           jTextField6.setVisible(false);
           jTextField7.setVisible(false);
           jTextField8.setVisible(false);
           jTextField9.setVisible(false);
           jTextField10.setVisible(false);
       }
       if(this.n < 5 ) {
           jTextField5.setVisible(false);
           jTextField10.setVisible(false);
           jTextField15.setVisible(false);
           jTextField20.setVisible(false);
           jTextField25.setVisible(false);
       }
       if(this.n < 4 ){
           jTextField4.setVisible(false);
           jTextField9.setVisible(false);
           jTextField14.setVisible(false);
           jTextField19.setVisible(false);
           jTextField24.setVisible(false);
       }
       if(this.n < 3 ){
           jTextField3.setVisible(false);
           jTextField8.setVisible(false);
           jTextField13.setVisible(false);
           jTextField18.setVisible(false);
           jTextField23.setVisible(false);
       }
       if(this.n < 2 ){
           jTextField2.setVisible(false);
           jTextField7.setVisible(false);
           jTextField12.setVisible(false);
           jTextField17.setVisible(false);
           jTextField22.setVisible(false);
       }
       
       
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int b = 0;
        int x = 0;
        int y = 0;
        for(char c : jTextField1.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField1.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField1.isVisible()==true&&b!=1){                    
        matrix[0][0] = Double.parseDouble(jTextField1.getText());
        }
        for(char c : jTextField2.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField2.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField2.isVisible()==true&&b!=1){
        matrix[0][1] = Double.parseDouble(jTextField2.getText());
        }
        for(char c : jTextField3.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField3.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField3.isVisible()==true&&b!=1){
        matrix[0][2] = Double.parseDouble(jTextField3.getText());
        }
       for(char c : jTextField4.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField4.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
         if(jTextField4.isVisible()==true&&b!=1){
        matrix[0][3] = Double.parseDouble(jTextField4.getText());
        }
        for(char c : jTextField5.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField5.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField5.isVisible()==true&&b!=1){
        matrix[0][4] = Double.parseDouble(jTextField5.getText());
        }
        for(char c : jTextField6.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField6.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField6.isVisible()==true&&b!=1){
        matrix[1][0] = Double.parseDouble(jTextField6.getText());
        }
        for(char c : jTextField7.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField7.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField7.isVisible()==true&&b!=1){
        matrix[1][1] = Double.parseDouble(jTextField7.getText());
        }
        for(char c : jTextField8.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField8.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField8.isVisible()==true&&b!=1){
        matrix[1][2] = Double.parseDouble(jTextField8.getText());
        }
       for(char c : jTextField9.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField9.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField9.isVisible()==true&&b!=1){
        matrix[1][3] = Double.parseDouble(jTextField9.getText());
        }
        for(char c : jTextField10.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField10.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField10.isVisible()==true&&b!=1){
        matrix[1][4] = Double.parseDouble(jTextField10.getText());
        }
        for(char c : jTextField11.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField11.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField11.isVisible()==true&&b!=1){
        matrix[2][0] = Double.parseDouble(jTextField11.getText());
        }
        for(char c : jTextField12.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField12.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField12.isVisible()==true&&b!=1){
        matrix[2][1] = Double.parseDouble(jTextField12.getText());
        }
        for(char c : jTextField13.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField13.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField13.isVisible()==true&&b!=1){
        matrix[2][2] = Double.parseDouble(jTextField13.getText());
        }
        for(char c : jTextField14.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField14.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField14.isVisible()==true&&b!=1){
        matrix[2][3] = Double.parseDouble(jTextField14.getText());
        }
        for(char c : jTextField15.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField15.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField15.isVisible()==true&&b!=1){
        matrix[2][4] = Double.parseDouble(jTextField15.getText());
        }
        for(char c : jTextField16.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField16.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField16.isVisible()==true&&b!=1){
        matrix[3][0] = Double.parseDouble(jTextField16.getText());
        }
        for(char c : jTextField17.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField17.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField17.isVisible()==true&&b!=1){
        matrix[3][1] = Double.parseDouble(jTextField17.getText());
        }
        for(char c : jTextField18.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField18.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField18.isVisible()==true&&b!=1){
        matrix[3][2] = Double.parseDouble(jTextField18.getText());
        }
        for(char c : jTextField19.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField19.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField19.isVisible()==true&&b!=1){
        matrix[3][3] = Double.parseDouble(jTextField19.getText());
        }
       for(char c : jTextField20.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField20.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField20.isVisible()==true&&b!=1){
        matrix[3][4] = Double.parseDouble(jTextField20.getText());
        }
        for(char c : jTextField21.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField21.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField21.isVisible()==true&&b!=1){
        matrix[4][0] = Double.parseDouble(jTextField21.getText());
        }
        for(char c : jTextField22.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField22.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField22.isVisible()==true&&b!=1){
        matrix[4][1] = Double.parseDouble(jTextField22.getText());
        }
        for(char c : jTextField23.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField23.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField23.isVisible()==true&&b!=1){
        matrix[4][2] = Double.parseDouble(jTextField23.getText());
        }
        for(char c : jTextField24.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField24.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField24.isVisible()==true&&b!=1){
        matrix[4][3] = Double.parseDouble(jTextField24.getText());
        }
        for(char c : jTextField25.getText().toCharArray())
        {
            if(c=='-'){
                if(x!=0){
                    b = 1;
                }
            }
            else if(c=='.'){
                y++;
                if(y==2){
                    b=1;
                }
                if(x==jTextField25.getText().length() - 1){
                    b = 1;
                }
            }
            else{
                if(!Character.isDigit(c)) b = 1;
            }
            x++;
        }
        x = 0;
        y = 0;
        if(jTextField25.isVisible()==true&&b!=1){
        matrix[4][4] = Double.parseDouble(jTextField25.getText());
        }
        if(b!=1){
        MatrisIslem matrisislem = new MatrisIslem(matrix,m,n);
        matrisislem.setVisible(true);
        }
        else{
        jTextField26.setText("Girilen Değerler Hatalı, Değerleri Tekrar Giriniz");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrisOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrisOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrisOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrisOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrisOlustur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
